"""Add is_threat column with server default

Revision ID: 2881802b37a3
Revises: 19d60d242a91
Create Date: 2025-05-22 17:49:57.391581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2881802b37a3'
down_revision = '19d60d242a91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_threat', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.drop_column('is_threat')

    # ### end Alembic commands ###
