"""Add is_threat and is_anomaly with server_default

Revision ID: 3cce8d833272
Revises: 2881802b37a3
Create Date: 2025-05-22 23:31:05.702566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cce8d833272'
down_revision = '2881802b37a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_anomaly', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.drop_column('is_anomaly')

    # ### end Alembic commands ###
