"""Add threat_intel column to Attack model

Revision ID: 3f597da4ba87
Revises: 6e091b60ed1d
Create Date: 2025-05-26 16:02:35.323343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f597da4ba87'
down_revision = '6e091b60ed1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threat_intel', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.drop_column('threat_intel')

    # ### end Alembic commands ###
