"""Refine Attack model fields and relationships

Revision ID: a45adc117513
Revises: cbe99035b9cb
Create Date: 2025-06-03 16:26:28.706707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'a45adc117513'
down_revision = 'cbe99035b9cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('honeypot_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('honeypot_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('threat_level', sa.String(length=50), nullable=True))
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('payload',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.alter_column('payload',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('threat_level')
        batch_op.drop_column('honeypot_type')
        batch_op.drop_column('honeypot_name')

    # ### end Alembic commands ###
