"""Add ML feature columns to Attack model

Revision ID: cbe99035b9cb
Revises: 837efc5ce40f
Create Date: 2025-06-01 11:05:29.970547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbe99035b9cb'
down_revision = '837efc5ce40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_path_length', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('http_method_encoded', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_sql_injection_pattern', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_xss_pattern', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_dir_trav_pattern', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('hour_of_day', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('day_of_week', sa.Integer(), nullable=True))

    with op.batch_alter_table('honeypots', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_honeypots_api_key', ['api_key'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('honeypots', schema=None) as batch_op:
        batch_op.drop_constraint('uq_honeypots_api_key', type_='unique')

    with op.batch_alter_table('attacks', schema=None) as batch_op:
        batch_op.drop_column('day_of_week')
        batch_op.drop_column('hour_of_day')
        batch_op.drop_column('is_dir_trav_pattern')
        batch_op.drop_column('is_xss_pattern')
        batch_op.drop_column('is_sql_injection_pattern')
        batch_op.drop_column('http_method_encoded')
        batch_op.drop_column('request_path_length')

    # ### end Alembic commands ###
